# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iOx2IbnFYBU_vlYrNo6r49GhgXQ4f_k1
"""

from setuptools import setup, find_packages
import os

# Leer el contenido de README.md para la descripción larga
readme_path = os.path.join(os.path.dirname(__file__), 'README.md')
if os.path.exists(readme_path):
    with open(readme_path, 'r', encoding='utf-8') as f:
        long_description = f.read()
else:
    long_description = 'Una librería para generar datos demográficos simulados de Colombia.'


setup(
    name='generador_datos_colombia',  # Nombre del paquete para pip
    version='0.1.0',                 # Versión inicial (puedes tomarla de __init__.py si prefieres)
    author='Tu Nombre o Alias',        # Cambia esto
    author_email='tu_email@ejemplo.com', # Cambia esto (opcional)
    description='Generador de datos demográficos simulados para Colombia.', # Descripción corta
    long_description=long_description, # Descripción larga desde README
    long_description_content_type='text/markdown',
    url='https://github.com/tu_usuario_github/generador_datos_colombia', # Cambia esto!
    # Busca automáticamente el paquete 'generador_datos_colombia' que contiene __init__.py
    packages=find_packages(include=['generador_datos_colombia', 'generador_datos_colombia.*']),
    classifiers=[
        'Development Status :: 3 - Alpha', # Estado del desarrollo
        'Intended Audience :: Education',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License', # Elige tu licencia (MIT es común)
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7', # Especifica versiones compatibles
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Operating System :: OS Independent',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: Utilities',
    ],
    python_requires='>=3.7',  # Versión mínima de Python requerida (por f-strings y otros)
    install_requires=[       # Lista de dependencias externas (si las hubiera)
        # En este caso, tu código solo usa la librería estándar de Python
        # (random, datetime, uuid), así que no se necesitan dependencias aquí.
    ],
    keywords='python, data generation, colombia, random data, simulation', # Palabras clave
)