# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iOx2IbnFYBU_vlYrNo6r49GhgXQ4f_k1
"""

# Importa la función principal desde generador.py para que esté disponible
# directamente al importar 'generador_datos_colombia'
from .generador import crear_base_datos_simulada

# Define la versión de tu librería
__version__ = "0.1.0"